require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.2
  Exclude:
    - 'spec/dummy/db/schema.rb'
    - 'vendor/**/*'

# Configuration parameters: Include.
# Include: **/*.gemspec
Gemspec/RequiredRubyVersion:
  Exclude:
    - 'goggles_db.gemspec'

# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 165

Metrics/AbcSize:
  Max: 26
  Exclude:
    - 'db/migrate/*'
    - 'app/validators/goggles_db/validation_error_tools.rb'
    - 'app/models/goggles_db/badge_payment.rb'

Metrics/BlockLength:
  Max: 40
  CountAsOne: ['array', 'heredoc']
  Exclude:
    - 'goggles_db.gemspec'
    - 'lib/tasks/*.rake'
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'lib/wrappers/timing.rb'
    - 'app/models/goggles_db/swimmer_stat.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/strategies/goggles_db/calculators/base_strategy.rb'
    - 'app/strategies/goggles_db/calculators/factory.rb'

Metrics/MethodLength:
  Max: 40
  CountAsOne: ['array', 'heredoc']

Metrics/ModuleLength:
  Max: 200
  # If Rubocop whines too much for a spec length, exclude the individual files:
  Exclude:
    - 'spec/models/goggles_db/import_queue_spec.rb'
    - 'spec/models/goggles_db/meeting_individual_result_spec.rb'
    - 'spec/models/goggles_db/meeting_spec.rb'
    - 'spec/models/goggles_db/season_spec.rb'
    - 'spec/models/goggles_db/swimmer_spec.rb'
    - 'spec/models/goggles_db/user_spec.rb'
    - 'spec/strategies/goggles_db/manager_checker_spec.rb'
    - 'spec/support/shared_calculators_examples.rb'

Naming/VariableNumber:
  Exclude:
    - 'db/migrate/20201121173221_rename_bool_fields_for_mevents_plus_more.rb'
    - 'db/migrate/20210130164719_rename_under_25_to_under25.rb'

Rake/MethodDefinitionInTask:
  Exclude:
    - 'lib/tasks/db_check.rake'
    - 'lib/tasks/db_dump_rebuild_reset.rake'
    - 'lib/tasks/normalize_*'

# This rule is simply stupid and needs to be kept disabled (most of the inline SQL will fail using squish)
Rails/SquishedSQLHeredocs:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/FactoryBot/SyntaxMethods:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 18

RSpec/NestedGroups:
  Max: 5

RSpec/PendingWithoutReason:
  Exclude:
    - 'spec/models/goggles_db/goggle_cup*'

Style/Documentation:
  Exclude:
    - 'db/migrate/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/goggles_db/application_controller.rb'
    - 'app/helpers/goggles_db/application_helper.rb'
    - 'app/mailers/goggles_db/application_mailer.rb'
    - 'app/models/goggles_db/application_record.rb'
    - 'app/models/goggles_db/user.rb'
    - 'lib/goggles_db.rb'
    - 'lib/goggles_db/engine.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/factories/**/*'
