version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1

common-config: &common-config
  working_directory: ~/goggles_db
  shell: /bin/bash --login
  # NOTE: make sure ENV vars on CircleCI include CC_TEST_REPORTER_ID
  #       for CodeClimate test coverage upload!
  #       (Otherwise the 'upload-coverage' step will fail.)
  docker:
    - image: cimg/ruby:3.1.4-node
      environment:
        RAILS_ENV: test
        BUNDLE_JOBS: 2
        BUNDLE_RETRY: 2
        BUNDLE_PATH: vendor/bundle
        PAGER: cat
    - image: cimg/mariadb:10.6.12
      environment:
        DATABASE_NAME: goggles_test
        DATABASE_USER: root
        PAGER: cat

common-db-setup: &common-db-setup
  name: DB setup
  command: |
    sudo apt update
    sudo apt-get install mysql-client
    mkdir -p tmp
    mv spec/dummy/config/database_ci.yml spec/dummy/config/database.yml
    dockerize -wait tcp://localhost:3306 -timeout 1m
    RAILS_ENV=test bin/rails app:db:rebuild from=test to=test
    RAILS_ENV=test bin/rails db:migrate
    ./tmp/cc-test-reporter before-build

jobs:
  persisted-data:
    <<: *common-config
    parallelism: 1
    steps:
      - run:
          name:  Setup persisted data
          command: |
            mkdir -p tmp
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter

  rubocop:
    <<: *common-config
    parallelism: 1
    steps:
      - checkout
      - ruby/install-deps:
          app-dir: ~/goggles_db
          key: goggles_db-v0600
      - ruby/rubocop-check:
          app-dir: ~/goggles_db
          label: Rubocop
          format: pacman

  brakeman:
    <<: *common-config
    parallelism: 1
    steps:
      - checkout
      - ruby/install-deps:
          app-dir: ~/goggles_db
          key: goggles_db-v0600
      - run:
          name: Brakeman
          command: |
            bundle exec brakeman -A6q -p spec/dummy

  zeitwerk:
    <<: *common-config
    parallelism: 1
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_db/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_db
          key: goggles_db-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: Zeitwerk check
          command: |
            bundle exec rake app:zeitwerk:check

  rspec-model:
    <<: *common-config
    parallelism: 3
    steps:
      - checkout
      - attach_workspace:
          at: ~/goggles_db/tmp
      - ruby/install-deps:
          app-dir: ~/goggles_db
          key: goggles_db-v0600
      - run:
          <<: *common-db-setup
      - run:
          name: RSpec - models
          command: |
            TEST_FILES=$(circleci tests glob "spec/models/**/*_spec.rb" | circleci tests split --split-by=timings)
            bundle exec spec/dummy/bin/rspec --profile 10 --color --order rand \
                        -f RspecJunitFormatter --out tmp/rspec-models.xml \
                        -f doc -- ${TEST_FILES}
            ./tmp/cc-test-reporter format-coverage -t simplecov \
                                   -o "tmp/codeclimate.rspec-models.$CIRCLE_NODE_INDEX.json"
            ls -l ./tmp
      - store_test_results:
          path: tmp
      - store_artifacts:
          path: tmp
      - persist_to_workspace:
          root: tmp
          paths:
            - tmp/codeclimate.*.json


  rspec-command:
    <<: *common-config
    steps:
      - checkout
      - ruby/install-deps:
          key: goggles_db-v0600
      - run:
          <<: *common-db-setup
      - ruby/rspec-test:
          label: RSpec - commands
          no_output_timeout: 5m
          # out-path: coverage/rspec-command
          tag: type:command
      # - store_test_results:
      #     path: coverage/rspec-command

  rspec-decorator:
    <<: *common-config
    steps:
      - checkout
      - ruby/install-deps:
          key: goggles_db-v0600
      - run:
          <<: *common-db-setup
      - ruby/rspec-test:
          label: RSpec - decorators
          no_output_timeout: 5m
          # out-path: coverage/rspec-decorator
          tag: type:decorator
      # - store_test_results:
      #     path: coverage/rspec-decorator

  rspec-strategy:
    <<: *common-config
    steps:
      - checkout
      - ruby/install-deps:
          key: goggles_db-v0600
      - run:
          <<: *common-db-setup
      - ruby/rspec-test:
          label: RSpec - strategies
          no_output_timeout: 5m
          # out-path: coverage/rspec-strategy
          tag: type:strategy
      # - store_test_results:
      #     path: coverage/rspec-strategy

  rspec-validator:
    <<: *common-config
    steps:
      - checkout
      - ruby/install-deps:
          key: goggles_db-v0600
      - run:
          <<: *common-db-setup
      - ruby/rspec-test:
          label: RSpec - validators
          no_output_timeout: 5m
          # out-path: coverage/rspec-validator
          tag: type:validator
      # - store_test_results:
      #     path: coverage/rspec-validator


  upload-coverage:
    <<: *common-config
    parallelism: 1
    steps:
      - attach_workspace:
          at: ~/goggles_db/tmp
      - run:
          name: CodeClimate upload
          command: |
            ls -l ./tmp
            ./tmp/cc-test-reporter sum-coverage -o - tmp/codeclimate.*.json | ./tmp/cc-test-reporter upload-coverage --debug --input -

  # deploy:
  #   # This is an example deploy job, not actually used by the workflow
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     # Replace this with steps to deploy to users
  #     - run:
  #         name: deploy
  #         command: '#e.g. ./deploy.sh'

workflows:
  full-build:
    jobs:
      - persisted-data
      # - brakeman:
      #     requires:
      #       - persisted-data
      # - rubocop:
      #     requires:
      #       - persisted-data
      # - zeitwerk:
      #     requires:
      #       - persisted-data

      - rspec-model:
          requires:
            - persisted-data
            # - brakeman
            # - rubocop
            # - zeitwerk

      - upload-coverage:
          requires:
            - rspec-model

      # - rspec-command:
      #     requires:
      #       - rspec-model
      # - rspec-decorator:
      #     requires:
      #       - rspec-model

      # - rspec-strategy:
      #     requires:
      #       - rspec-command
      #       - rspec-decorator
      # - rspec-validator:
      #     requires:
      #       - rspec-command
      #       - rspec-decorator

      # - coverage-upload:
      #     requires:
      #       - rspec-model
      #       - rspec-command
      #       - rspec-decorator
      #       - rspec-strategy
      #       - rspec-validator

    # - deploy:
    #     requires:
    #       - rspec
